-- MH SOLAR Daily Rates database
-- Run this once in Supabase SQL Editor.
create table if not exists public.solar_rates (
  id bigint generated by default as identity primary key,
  product text not null,
  category text not null check (category in ('panel','inverter','battery','wire','accessory')),
  unit text not null default 'per unit',
  price numeric(12,2) not null default 0,
  status text not null default 'In Stock',
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.solar_rates enable row level security;

drop policy if exists "Public can read rates" on public.solar_rates;
create policy "Public can read rates" on public.solar_rates for select using (true);

drop policy if exists "Public can update rates" on public.solar_rates;
create policy "Public can update rates" on public.solar_rates for update using (true) with check (true);

drop policy if exists "Public can insert rates" on public.solar_rates;
create policy "Public can insert rates" on public.solar_rates for insert with check (true);

drop policy if exists "Public can delete rates" on public.solar_rates;
create policy "Public can delete rates" on public.solar_rates for delete using (true);

insert into public.solar_rates (product,category,unit,price,status)
select * from (values
('Astronergy 585W N-Type Bifacial','panel','per panel',23985,'In Stock'),
('Jinko 585W N-Type','panel','per watt',41,'Reference'),
('Canadian 585/590W N-Type TOPCon','panel','per panel',25330,'In Stock'),
('Solar Inverter 3kW','inverter','per unit',0,'Update'),
('Solar Inverter 5kW','inverter','per unit',0,'Update'),
('Lithium Battery 5kWh','battery','per unit',0,'Update'),
('Lithium Battery 10kWh','battery','per unit',0,'Update'),
('DC Solar Cable 6mm','wire','per meter',0,'Update'),
('DC Solar Cable 10mm','wire','per meter',0,'Update'),
('MC4 Pair','accessory','per pair',0,'Update'),
('DC Breaker / SPD','accessory','per unit',0,'Update')
) as v(product,category,unit,price,status)
where not exists (select 1 from public.solar_rates);
